export const INGREDIENTS_REQUEST_SUCCESS = "INGREDIENTS_REQUEST_SUCCESS";
export const INGREDIENTS_REQUEST_ERROR = "INGREDIENTS_REQUEST_ERROR";
export const INGREDIENTS_COUNT_RESET = "INGREDIENTS_COUNT_RESET";
export const INGREDIENTS_PLUS_COUNT = "INGREDIENTS_PLUS_COUNT";
export const INGREDIENTS_MINUS_COUNT = "INGREDIENTS_MINUS_COUNT";

export const CONSTRUCTOR_ADD_BUN = "CONSTRUCTOR_ADD_BUN";
export const CONSTRUCTOR_ADD_INDGREDIENT = "CONSTRUCTOR_ADD_INDGREDIENT";
export const CONSTRUCTOR_REMOVE_INGREDIENT = "CONSTRUCTOR_REMOVE_INGREDIENT";
export const CONSTRUCTOR_UPDATE = "CONSTRUCTOR_UPDATE";
export const CONSTRUCTOR_RESET = "CONSTRUCTOR_RESET";

export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_REQUEST_SUCCESS = "FORGOT_PASSWORD_REQUEST_SUCCESS";
export const FORGOT_PASSWORD_REQUEST_ERROR = "FORGOT_PASSWORD_REQUEST_ERROR";
export const FORGOT_PASSWORD_RESET = "FORGOT_PASSWORD_RESET";

export const INGREDIENT_MODAL_OPEN = "INGREDIENT_MODAL_OPEN";
export const INGREDIENT_MODAL_CLOSE = "INGREDIENT_MODAL_CLOSE";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_ERROR = "LOGIN_REQUEST_ERROR";
export const LOGIN_STATE_RESET = "LOGIN_STATE_RESET";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_REQUEST_SUCCESS = "LOGOUT_REQUEST_SUCCESS";
export const LOGOUT_REQUEST_ERROR = "LOGOUT_REQUEST_ERROR";
export const LOGOUT_STATE_RESET = "LOGOUT_STATE_RESET";

export const ORDER_NUMBER_REQUEST_SUCCESS = "ORDER_NUMBER_REQUEST_SUCCESS";
export const ORDER_NUMBER_REQUEST_ERROR = "ORDER_NUMBER_REQUEST_ERROR";
export const ORDER_NUMBER_RESET = "ORDER_NUMBER_RESET";

export const PROFILE_REQUEST = "PROFILE_REQUEST";
export const PROFILE_REQUEST_SUCCESS = "PROFILE_REQUEST_SUCCESS";
export const PROFILE_REQUEST_ERROR = "PROFILE_REQUEST_ERROR";
export const PROFILE_STATE_RESET = "PROFILE_STATE_RESET";

export const RESET_PASSWORD_REQUEST = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_REQUEST_SUCCESS = "RESET_PASSWORD_REQUEST_SUCCESS";
export const RESET_PASSWORD_REQUEST_ERROR = "RESET_PASSWORD_REQUEST_ERROR";
export const RESET_PASSWORD_INITIAL = "RESET_PASSWORD_INITIAL";

export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_REQUEST_SUCCESS = "SIGN_UP_REQUEST_SUCCESS";
export const SIGN_UP_REQUEST_ERROR = "SIGN_UP_REQUEST_ERROR";

export const UPDATE_TOKEN_REQUEST = "UPDATE_TOKEN_REQUEST";
export const UPDATE_TOKEN_REQUEST_SUCCESS = "UPDATE_TOKEN_REQUEST_SUCCESS";
export const UPDATE_TOKEN_REQUEST_ERROR = "UPDATE_TOKEN_REQUEST_ERROR";

export const GET_PROFILE = "GET_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
