export const INGREDIENTS_REQUEST = "INGREDIENTS_REQUEST";
export const INGREDIENTS_REQUEST_SUCCESS = "INGREDIENTS_REQUEST_SUCCESS";
export const INGREDIENTS_REQUEST_FAILED = "INGREDIENTS_REQUEST_FAILED";
export const INGREDIENTS_PLUS_COUNT = "INGREDIENTS_PLUS_COUNT";
export const INGREDIENTS_MINUS_COUNT = "INGREDIENTS_MINUS_COUNT";

export const CONSTRUCTOR_ADD_BUN = "CONSTRUCTOR_ADD_BUN";
export const CONSTRUCTOR_ADD_INDGREDIENT = "CONSTRUCTOR_ADD_INDGREDIENT";
export const CONSTRUCTOR_REMOVE_INGREDIENT = "CONSTRUCTOR_REMOVE_INGREDIENT";
export const CONSTRUCTOR_UPDATE = "CONSTRUCTOR_UPDATE";

export const INGREDIENT_MODAL_OPEN = "INGREDIENT_MODAL_OPEN";
export const INGREDIENT_MODAL_CLOSE = "INGREDIENT_MODAL_CLOSE";

export const ORDER_NUMBER_REQUEST = "ORDER_NUMBER_REQUEST";
export const ORDER_NUMBER_REQUEST_SUCCESS = "ORDER_NUMBER_REQUEST_SUCCESS";
export const ORDER_NUMBER_REQUEST_FAILD = "ORDER_NUMBER_REQUEST_FAILD";
export const ORDER_NUMBER_RESET = "ORDER_NUMBER_RESET";
