export const INGREDIENTS_REQUEST_SUCCESS: "INGREDIENTS_REQUEST_SUCCESS" =
  "INGREDIENTS_REQUEST_SUCCESS";
export const INGREDIENTS_REQUEST_ERROR: "INGREDIENTS_REQUEST_ERROR" = "INGREDIENTS_REQUEST_ERROR";
export const INGREDIENTS_COUNT_RESET: "INGREDIENTS_COUNT_RESET" = "INGREDIENTS_COUNT_RESET";

export const INGREDIENTS_PLUS_COUNT: "INGREDIENTS_PLUS_COUNT" = "INGREDIENTS_PLUS_COUNT";
export const INGREDIENTS_MINUS_COUNT: "INGREDIENTS_MINUS_COUNT" = "INGREDIENTS_MINUS_COUNT";
