export const CONSTRUCTOR_ADD_BUN: "CONSTRUCTOR_ADD_BUN" = "CONSTRUCTOR_ADD_BUN";

export const CONSTRUCTOR_ADD_INDGREDIENT: "CONSTRUCTOR_ADD_INDGREDIENT" =
  "CONSTRUCTOR_ADD_INDGREDIENT";
export const CONSTRUCTOR_REMOVE_INGREDIENT: "CONSTRUCTOR_REMOVE_INGREDIENT" =
  "CONSTRUCTOR_REMOVE_INGREDIENT";

export const CONSTRUCTOR_UPDATE: "CONSTRUCTOR_UPDATE" = "CONSTRUCTOR_UPDATE";
export const CONSTRUCTOR_RESET: "CONSTRUCTOR_RESET" = "CONSTRUCTOR_RESET";
