export const FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST" = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_REQUEST_SUCCESS: "FORGOT_PASSWORD_REQUEST_SUCCESS" =
  "FORGOT_PASSWORD_REQUEST_SUCCESS";
export const FORGOT_PASSWORD_REQUEST_ERROR: "FORGOT_PASSWORD_REQUEST_ERROR" =
  "FORGOT_PASSWORD_REQUEST_ERROR";

export const FORGOT_PASSWORD_RESET: "FORGOT_PASSWORD_RESET" = "FORGOT_PASSWORD_RESET";
