export const LOGIN_REQUEST: "LOGIN_REQUEST" = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS: "LOGIN_REQUEST_SUCCESS" = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_ERROR: "LOGIN_REQUEST_ERROR" = "LOGIN_REQUEST_ERROR";

export const LOGIN_STATE_RESET: "LOGIN_STATE_RESET" = "LOGIN_STATE_RESET";

export const LOGOUT_REQUEST_ERROR: "LOGOUT_REQUEST_ERROR" = "LOGOUT_REQUEST_ERROR";
