export const ORDER_NUMBER_REQUEST_SUCCESS: "ORDER_NUMBER_REQUEST_SUCCESS" =
  "ORDER_NUMBER_REQUEST_SUCCESS";
export const ORDER_NUMBER_REQUEST_ERROR: "ORDER_NUMBER_REQUEST_ERROR" =
  "ORDER_NUMBER_REQUEST_ERROR";

export const ORDER_NUMBER_RESET: "ORDER_NUMBER_RESET" = "ORDER_NUMBER_RESET";
