export const PROFILE_REQUEST: "PROFILE_REQUEST" = "PROFILE_REQUEST";
export const PROFILE_REQUEST_SUCCESS: "PROFILE_REQUEST_SUCCESS" = "PROFILE_REQUEST_SUCCESS";
export const PROFILE_REQUEST_ERROR: "PROFILE_REQUEST_ERROR" = "PROFILE_REQUEST_ERROR";

export const PROFILE_STATE_RESET: "PROFILE_STATE_RESET" = "PROFILE_STATE_RESET";
