export const RESET_PASSWORD_REQUEST: "RESET_PASSWORD_REQUEST" = "RESET_PASSWORD_REQUEST";
export const RESET_PASSWORD_REQUEST_SUCCESS: "RESET_PASSWORD_REQUEST_SUCCESS" =
  "RESET_PASSWORD_REQUEST_SUCCESS";
export const RESET_PASSWORD_REQUEST_ERROR: "RESET_PASSWORD_REQUEST_ERROR" =
  "RESET_PASSWORD_REQUEST_ERROR";

export const RESET_PASSWORD_INITIAL: "RESET_PASSWORD_INITIAL" = "RESET_PASSWORD_INITIAL";
