export const SIGN_UP_REQUEST: "SIGN_UP_REQUEST" = "SIGN_UP_REQUEST";
export const SIGN_UP_REQUEST_SUCCESS: "SIGN_UP_REQUEST_SUCCESS" = "SIGN_UP_REQUEST_SUCCESS";
export const SIGN_UP_REQUEST_ERROR: "SIGN_UP_REQUEST_ERROR" = "SIGN_UP_REQUEST_ERROR";
