export const TOKEN_REQUEST: "TOKEN_REQUEST" = "TOKEN_REQUEST";
export const TOKEN_REQUEST_SUCCESS: "TOKEN_REQUEST_SUCCESS" = "TOKEN_REQUEST_SUCCESS";
export const TOKEN_REQUEST_ERROR: "TOKEN_REQUEST_ERROR" = "TOKEN_REQUEST_ERROR";

export const GET_PROFILE: "GET_PROFILE" = "GET_PROFILE";
export const UPDATE_PROFILE: "UPDATE_PROFILE" = "UPDATE_PROFILE";
